global_defs {
    router_id postgres-replica
    script_user root
    enable_script_security
}

vrrp_script chk_pg_primary {
    script "/usr/local/bin/check-pg-primary.sh"
    interval 2
    weight 20
    fall 3
    rise 2
}

vrrp_instance VI_PG {
    state BACKUP
    interface eth0
    virtual_router_id 52
    priority 90
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass PgVip52
    }
    virtual_ipaddress {
        10.92.3.23/24
    }
    track_script {
        chk_pg_primary
    }
}
